const characters = {
    "Alear" : {
        Hp: 60,
        Str: 35,
        Mag: 20,
        Dex: 45,
        Spd: 50,
        Def: 40,
        Res: 25,
        Lck: 25,
        Bld: 5,
        chapter: 1,
        maxMod: {
            Str: 1,
            Mag: 0,
            Dex: 1,
            Spd: 1,
            Def: 0,
            Res: 0,
            Lck: 0,
        },
        unique: "Divine Dragon"
    },
    "Vander" : {
        Hp: 60,
        Str: 25,
        Mag: 10,
        Dex: 25,
        Spd: 35,
        Def: 35,
        Res: 20,
        Lck: 10,
        Bld: 5,
        chapter: 1,
        maxMod: {
            Str: 1,
            Mag: -1,
            Dex: 1,
            Spd: -2,
            Def: 3,
            Res: -2,
            Lck: 0,
        },
        unique: false
    },
    "Clanne" : {
        Hp: 40,
        Str: 35,
        Mag: 10,
        Dex: 40,
        Spd: 50,
        Def: 30,
        Res: 25,
        Lck: 20,
        Bld: 5,
        chapter: 2,
        maxMod: {
            Str: 1,
            Mag: -1,
            Dex: 2,
            Spd: 2,
            Def: -2,
            Res: -1,
            Lck: 0,
        },
        unique: false
    },
    "Framme" : {
        Hp: 55,
        Str: 30,
        Mag: 25,
        Dex: 35,
        Spd: 55,
        Def: 25,
        Res: 30,
        Lck: 25,
        Bld: 0,
        chapter: 2,
        maxMod: {
            Str: 0,
            Mag: 1,
            Dex: -1,
            Spd: 2,
            Def: -1,
            Res: -1,
            Lck: 1,
        },
        unique: false
    },
    "Alfred" : {
        Hp: 65,
        Str: 40,
        Mag: 5,
        Dex: 35,
        Spd: 40,
        Def: 40,
        Res: 20,
        Lck: 40,
        Bld: 10,
        chapter: 3,
        maxMod: {
            Str: 2,
            Mag: -1,
            Dex: 1,
            Spd: 0,
            Def: 2,
            Res: -2,
            Lck: -1,
        },
        unique: "Avenir"
    },
    "Etie" : {
        Hp: 45,
        Str: 40,
        Mag: 0,
        Dex: 25,
        Spd: 35,
        Def: 25,
        Res: 30,
        Lck: 25,
        Bld: 5,
        chapter: 3,
        maxMod: {
            Str: 2,
            Mag: -2,
            Dex: 2,
            Spd: 0,
            Def: 0,
            Res: -1,
            Lck: -1,
        },
        unique: false
    },
    "Boucheron" : {
        Hp: 85,
        Str: 20,
        Mag: 0,
        Dex: 50,
        Spd: 45,
        Def: 35,
        Res: 20,
        Lck: 15,
        Bld: 20,
        chapter: 3,
        maxMod: {
            Str: 1,
            Mag: 0,
            Dex: 2,
            Spd: 2,
            Def: -2,
            Res: 0,
            Lck: -2,
        },
        unique: false
    },
    "Celine" : {
        Hp: 50,
        Str: 35,
        Mag: 25,
        Dex: 30,
        Spd: 45,
        Def: 30,
        Res: 40,
        Lck: 50,
        Bld: 5,
        chapter: 4,
        maxMod: {
            Str: -2,
            Mag: 2,
            Dex: -2,
            Spd: 1,
            Def: -3,
            Res: 1,
            Lck: 3,
        },
        unique: "Vidame"
    },
    "Chloe" : {
        Hp: 75,
        Str: 25,
        Mag: 35,
        Dex: 40,
        Spd: 55,
        Def: 30,
        Res: 25,
        Lck: 25,
        Bld: 5,
        chapter: 4,
        maxMod: {
            Str: -2,
            Mag: 1,
            Dex: 0,
            Spd: 3,
            Def: -1,
            Res: 0,
            Lck: 0,
        },
        unique: false
    },
    "Louis" : {
        Hp: 75,
        Str: 40,
        Mag: 0,
        Dex: 25,
        Spd: 25,
        Def: 50,
        Res: 20,
        Lck: 25,
        Bld: 15,
        chapter: 4,
        maxMod: {
            Str: 1,
            Mag: 0,
            Dex: -1,
            Spd: -2,
            Def: 3,
            Res: -2,
            Lck: 1,
        },
        unique: false
    },
    "Yunaka" : {
        Hp: 50,
        Str: 35,
        Mag: 25,
        Dex: 40,
        Spd: 45,
        Def: 15,
        Res: 45,
        Lck: 25,
        Bld: 5,
        chapter: 6,
        maxMod: {
            Str: -1,
            Mag: 0,
            Dex: 1,
            Spd: 2,
            Def: -2,
            Res: 2,
            Lck: -1,
        },
        unique: false,
        img: 'yunaka.png'
    },
    "Alcryst" : {
        Hp: 65,
        Str: 30,
        Mag: 10,
        Dex: 40,
        Spd: 45,
        Def: 30,
        Res: 20,
        Lck: 15,
        Bld: 10,
        chapter: 7,
        maxMod: {
            Str: 1,
            Mag: -1,
            Dex: 3,
            Spd: 0,
            Def: 1,
            Res: -2,
            Lck: -1,
        },
        unique: "Tireur d'elite"
    },
    "Citrinne" : {
        Hp: 45,
        Str: 10,
        Mag: 40,
        Dex: 25,
        Spd: 30,
        Def: 20,
        Res: 40,
        Lck: 25,
        Bld: 5,
        chapter: 7,
        maxMod: {
            Str: -1,
            Mag: 3,
            Dex: 0,
            Spd: -1,
            Def: -2,
            Res: 2,
            Lck: 0,
        },
        unique: false
    },
    "Lapis" : {
        Hp: 55,
        Str: 25,
        Mag: 20,
        Dex: 35,
        Spd: 55,
        Def: 35,
        Res: 30,
        Lck: 25,
        Bld: 5,
        chapter: 7,
        maxMod: {
            Str: -2,
            Mag: -2,
            Dex: 2,
            Spd: 3,
            Def: 0,
            Res: 0,
            Lck: 0,
        },
        unique: false
    },
    "Diamant" : {
        Hp: 75,
        Str: 30,
        Mag: 15,
        Dex: 20,
        Spd: 40,
        Def: 40,
        Res: 25,
        Lck: 20,
        Bld: 15,
        chapter: 8,
        maxMod: {
            Str: 2,
            Mag: -1,
            Dex: -1,
            Spd: 0,
            Def: 2,
            Res: -1,
            Lck: 0,
        },
        unique: "Successeur"
    },
    "Amber" : {
        Hp: 65,
        Str: 45,
        Mag: 0,
        Dex: 25,
        Spd: 30,
        Def: 35,
        Res: 5,
        Lck: 35,
        Bld: 15,
        chapter: 8,
        maxMod: {
            Str: 2,
            Mag: -1,
            Dex: -1,
            Spd: -1,
            Def: 1,
            Res: -1,
            Lck: 1,
        },
        unique: false
    },
    "Jade" : {
        Hp: 55,
        Str: 35,
        Mag: 25,
        Dex: 35,
        Spd: 30,
        Def: 40,
        Res: 30,
        Lck: 20,
        Bld: 10,
        chapter: 9,
        maxMod: {
            Str: 2,
            Mag: -1,
            Dex: -1,
            Spd: -1,
            Def: 1,
            Res: -1,
            Lck: 1,
        },
        unique: false
    },
    "Ivy" : {
        Hp: 55,
        Str: 25,
        Mag: 30,
        Dex: 25,
        Spd: 40,
        Def: 30,
        Res: 35,
        Lck: 15,
        Bld: 10,
        chapter: 11,
        maxMod: {
            Str: 0,
            Mag: 2,
            Dex: -2,
            Spd: 0,
            Def: 2,
            Res: 2,
            Lck: -3,
        },
        unique: "Lindwurm"
    },
    "Kagetsu" : {
        Hp: 60,
        Str: 30,
        Mag: 15,
        Dex: 50,
        Spd: 50,
        Def: 40,
        Res: 25,
        Lck: 40,
        Bld: 10,
        chapter: 11,
        maxMod: {
            Str: -1,
            Mag: -1,
            Dex: 2,
            Spd: 2,
            Def: 0,
            Res: -2,
            Lck: 1,
        },
        unique: false
    },
    "Zelkov" : {
        Hp: 65,
        Str: 35,
        Mag: 15,
        Dex: 40,
        Spd: 35,
        Def: 35,
        Res: 15,
        Lck: 25,
        Bld: 10,
        chapter: 11,
        maxMod: {
            Str: 0,
            Mag: -1,
            Dex: 2,
            Spd: 0,
            Def: 0,
            Res: -1,
            Lck: 1,
        },
        unique: false
    },
    "Fogado" : {
        Hp: 60,
        Str: 30,
        Mag: 25,
        Dex: 30,
        Spd: 55,
        Def: 30,
        Res: 35,
        Lck: 25,
        Bld: 10,
        chapter: 12,
        maxMod: {
            Str: -1,
            Mag: -1,
            Dex: 0,
            Spd: 3,
            Def: -1,
            Res: 1,
            Lck: 0,
        },
        unique: "Cupido"
    },
    "Pandreo" : {
        Hp: 60,
        Str: 5,
        Mag: 30,
        Dex: 45,
        Spd: 45,
        Def: 15,
        Res: 55,
        Lck: 30,
        Bld: 15,
        chapter: 12,
        maxMod: {
            Str: -3,
            Mag: 2,
            Dex: 0,
            Spd: -1,
            Def: -2,
            Res: 3,
            Lck: 2,
        },
        unique: false
    },
    "Bunet" : {
        Hp: 65,
        Str: 30,
        Mag: 10,
        Dex: 40,
        Spd: 35,
        Def: 45,
        Res: 25,
        Lck: 40,
        Bld: 10,
        chapter: 12,
        maxMod: {
            Str: 1,
            Mag: -3,
            Dex: 1,
            Spd: 0,
            Def: 2,
            Res: -1,
            Lck: 1,
        },
        unique: false
    },
    "Timerra" : {
        Hp: 55,
        Str: 25,
        Mag: 25,
        Dex: 45,
        Spd: 45,
        Def: 30,
        Res: 30,
        Lck: 30,
        Bld: 10,
        chapter: 13,
        maxMod: {
            Str: -1,
            Mag: -1,
            Dex: 3,
            Spd: 0,
            Def: 2,
            Res: -3,
            Lck: 1,
        },
        unique: "Picket"
    },
    "Panette" : {
        Hp: 75,
        Str: 45,
        Mag: 10,
        Dex: 40,
        Spd: 25,
        Def: 30,
        Res: 15,
        Lck: 20,
        Bld: 15,
        chapter: 13,
        maxMod: {
            Str: 3,
            Mag: -1,
            Dex: 0,
            Spd: 0,
            Def: 0,
            Res: -1,
            Lck: 0,
        },
        unique: false
    },
    "Merrin" : {
        Hp: 55,
        Str: 25,
        Mag: 25,
        Dex: 40,
        Spd: 50,
        Def: 30,
        Res: 30,
        Lck: 25,
        Bld: 10,
        chapter: 13,
        maxMod: {
            Str: -1,
            Mag: -1,
            Dex: 1,
            Spd: 2,
            Def: -1,
            Res: 0,
            Lck: 1,
        },
        unique: false
    },
    "Hortensia" : {
        Hp: 40,
        Str: 20,
        Mag: 20,
        Dex: 35,
        Spd: 50,
        Def: 25,
        Res: 55,
        Lck: 50,
        Bld: 0,
        chapter: 14,
        maxMod: {
            Str: -2,
            Mag: 0,
            Dex: 0,
            Spd: 1,
            Def: -3,
            Res: 3,
            Lck: 2,
        },
        unique: "Sleipnir Rider"
    },
    "Rosado" : {
        Hp: 75,
        Str: 45,
        Mag: 25,
        Dex: 40,
        Spd: 45,
        Def: 30,
        Res: 30,
        Lck: 20,
        Bld: 5,
        chapter: 16,
        maxMod: {
            Str: 3,
            Mag: -2,
            Dex: 1,
            Spd: 0,
            Def: 1,
            Res: -2,
            Lck: 0,
        },
        unique: false
    },
    "Seadall" : {
        Hp: 55,
        Str: 25,
        Mag: 15,
        Dex: 25,
        Spd: 50,
        Def: 25,
        Res: 25,
        Lck: 35,
        Bld: 10,
        chapter: 16,
        maxMod: {
            Str: 0,
            Mag: -2,
            Dex: -1,
            Spd: 2,
            Def: 0,
            Res: 0,
            Lck: 2,
        },
        unique: "Dancer"
    },
    "Goldmary" : {
        Hp: 65,
        Str: 30,
        Mag: 5,
        Dex: 25,
        Spd: 25,
        Def: 55,
        Res: 25,
        Lck: 25,
        Bld: 5,
        chapter: 16,
        maxMod: {
            Str: 1,
            Mag: -3,
            Dex: 0,
            Spd: 0,
            Def: 2,
            Res: -1,
            Lck: 2,
        },
        unique: false
    },
    "Lindon" : {
        Hp: 65,
        Str: 25,
        Mag: 25,
        Dex: 25,
        Spd: 40,
        Def: 25,
        Res: 40,
        Lck: 15,
        Bld: 10,
        chapter: 18,
        maxMod: {
            Str: 0,
            Mag: 2,
            Dex: -1,
            Spd: 0,
            Def: -2,
            Res: 2,
            Lck: 0,
        },
        unique: false
    },
    "Saphir" : {
        Hp: 80,
        Str: 35,
        Mag: 0,
        Dex: 25,
        Spd: 30,
        Def: 30,
        Res: 5,
        Lck: 20,
        Bld: 10,
        chapter: 19,
        maxMod: {
            Str: 2,
            Mag: -2,
            Dex: 0,
            Spd: 1,
            Def: 1,
            Res: -2,
            Lck: 0,
        },
        unique: false
    },
    "Veyle" : {
        Hp: 40,
        Str: 25,
        Mag: 45,
        Dex: 35,
        Spd: 30,
        Def: 25,
        Res: 35,
        Lck: 20,
        Bld: 0,
        chapter: 22,
        maxMod: {
            Str: 0,
            Mag: 3,
            Dex: 0,
            Spd: -1,
            Def: 0,
            Res: 3,
            Lck: -2,
        },
        unique: "Fell Child"
    },
    "Mauvier" : {
        Hp: 70,
        Str: 35,
        Mag: 40,
        Dex: 40,
        Spd: 35,
        Def: 50,
        Res: 45,
        Lck: 15,
        Bld: 15,
        chapter: 21,
        maxMod: {
            Str: 1,
            Mag: 2,
            Dex: 1,
            Spd: -2,
            Def: 1,
            Res: 1,
            Lck: -2,
        },
        unique: false
    },
    "Anna" : {
        Hp: 55,
        Str: 15,
        Mag: 50,
        Dex: 50,
        Spd: 50,
        Def: 20,
        Res: 35,
        Lck: 45,
        Bld: 5,
        chapter: 7,
        maxMod: {
            Str: 0,
            Mag: 1,
            Dex: 1,
            Spd: 1,
            Def: -2,
            Res: -1,
            Lck: 1,
        },
        unique: false
    },
    "Jean" : {
        Hp: 50,
        Str: 20,
        Mag: 20,
        Dex: 35,
        Spd: 40,
        Def: 25,
        Res: 20,
        Lck: 25,
        Bld: 5,
        chapter: 6,
        maxMod: {
            Str: 0,
            Mag: 2,
            Dex: -1,
            Spd: -1,
            Def: 0,
            Res: 0,
            Lck: 1,
        },
        unique: false
    },
}

export default characters;