const init = [
        {
            "name": "Divine Dragon",
            "HP": 40,
            "Str": 17,
            "Mag": 4,
            "Dex": 23,
            "Spd": 25,
            "Def": 21,
            "Res": 10,
            "Lck": 12,
            "Bld": 5,
            "rating": 117
        },
        {
            "name": "Swordmaster",
            "HP": 40,
            "Str": 17,
            "Mag": 5,
            "Dex": 24,
            "Spd": 26,
            "Def": 19,
            "Res": 11,
            "Lck": 12,
            "Bld": 5,
            "rating": 119
        },
        {
            "name": "Halberdier",
            "HP": 40,
            "Str": 18,
            "Mag": 6,
            "Dex": 25,
            "Spd": 24,
            "Def": 22,
            "Res": 9,
            "Lck": 11,
            "Bld": 5,
            "rating": 120
        },
        {
            "name": "Royal Knight",
            "HP": 39,
            "Str": 17,
            "Mag": 7,
            "Dex": 24,
            "Spd": 25,
            "Def": 20,
            "Res": 12,
            "Lck": 12,
            "Bld": 5,
            "rating": 122
        },
        {
            "name": "Hero",
            "HP": 41,
            "Str": 18,
            "Mag": 5,
            "Dex": 23,
            "Spd": 24,
            "Def": 19,
            "Res": 10,
            "Lck": 13,
            "Bld": 5,
            "rating": 117
        },
        {
            "name": "Berserker",
            "HP": 44,
            "Str": 21,
            "Mag": 5,
            "Dex": 22,
            "Spd": 24,
            "Def": 19,
            "Res": 8,
            "Lck": 10,
            "Bld": 7,
            "rating": 116
        },
        {
            "name": "Warrior",
            "HP": 43,
            "Str": 19,
            "Mag": 5,
            "Dex": 23,
            "Spd": 25,
            "Def": 21,
            "Res": 10,
            "Lck": 10,
            "Bld": 6,
            "rating": 119
        },
        {
            "name": "Sniper",
            "HP": 41,
            "Str": 18,
            "Mag": 4,
            "Dex": 27,
            "Spd": 24,
            "Def": 21,
            "Res": 8,
            "Lck": 12,
            "Bld": 5,
            "rating": 119
        },
        {
            "name": "Bow Knight",
            "HP": 40,
            "Str": 18,
            "Mag": 4,
            "Dex": 25,
            "Spd": 26,
            "Def": 19,
            "Res": 11,
            "Lck": 13,
            "Bld": 5,
            "rating": 121
        },
        {
            "name": "General",
            "HP": 43,
            "Str": 19,
            "Mag": 5,
            "Dex": 24,
            "Spd": 18,
            "Def": 25,
            "Res": 9,
            "Lck": 10,
            "Bld": 7,
            "rating": 117
        },
        {
            "name": "Great Knight",
            "HP": 42,
            "Str": 18,
            "Mag": 4,
            "Dex": 24,
            "Spd": 22,
            "Def": 24,
            "Res": 10,
            "Lck": 12,
            "Bld": 6,
            "rating": 120
        },
        {
            "name": "Paladin",
            "HP": 41,
            "Str": 19,
            "Mag": 5,
            "Dex": 23,
            "Spd": 25,
            "Def": 22,
            "Res": 11,
            "Lck": 12,
            "Bld": 5,
            "rating": 122
        },
        {
            "name": "Wolf Knight",
            "HP": 40,
            "Str": 16,
            "Mag": 4,
            "Dex": 24,
            "Spd": 26,
            "Def": 20,
            "Res": 12,
            "Lck": 14,
            "Bld": 5,
            "rating": 121
        },
        {
            "name": "Sage",
            "HP": 38,
            "Str": 15,
            "Mag": 10,
            "Dex": 22,
            "Spd": 23,
            "Def": 19,
            "Res": 14,
            "Lck": 13,
            "Bld": 5,
            "rating": 121
        },
        {
            "name": "Mage Knight",
            "HP": 39,
            "Str": 16,
            "Mag": 9,
            "Dex": 21,
            "Spd": 23,
            "Def": 21,
            "Res": 13,
            "Lck": 11,
            "Bld": 4,
            "rating": 118
        },
        {
            "name": "Martial Master",
            "HP": 39,
            "Str": 17,
            "Mag": 8,
            "Dex": 21,
            "Spd": 22,
            "Def": 22,
            "Res": 14,
            "Lck": 13,
            "Bld": 5,
            "rating": 122
        },
        {
            "name": "High Priest",
            "HP": 38,
            "Str": 15,
            "Mag": 9,
            "Dex": 22,
            "Spd": 23,
            "Def": 19,
            "Res": 14,
            "Lck": 16,
            "Bld": 5,
            "rating": 123
        },
        {
            "name": "Griffin Knight",
            "HP": 38,
            "Str": 18,
            "Mag": 7,
            "Dex": 24,
            "Spd": 26,
            "Def": 19,
            "Res": 12,
            "Lck": 13,
            "Bld": 5,
            "rating": 124
        },
        {
            "name": "Wyvern Knight",
            "HP": 42,
            "Str": 19,
            "Mag": 4,
            "Dex": 23,
            "Spd": 23,
            "Def": 23,
            "Res": 9,
            "Lck": 12,
            "Bld": 6,
            "rating": 119
        },
        {
            "name": "Thief",
            "HP": 39,
            "Str": 18,
            "Mag": 5,
            "Dex": 25,
            "Spd": 25,
            "Def": 22,
            "Res": 9,
            "Lck": 13,
            "Bld": 5,
            "rating": 122
        }
]

export default init;