const promotes = {
    "Divine Dragon" : {
        name: "Divine Dragon",
        Hp: 10,
        Str: 10,
        Mag: 0,
        Dex: 10,
        Spd: 15,
        Def: 10,
        Res: 10,
        Lck: 5,
        Bld: 5,
        caps: {
            Hp: 68,
            Str: 41,
            Mag: 25,
            Dex: 36,
            Spd: 43,
            Def: 35,
            Res: 25,
            Lck: 35,
            Bld: 13,
        },
        unique: true,
    },
    "Fell Child" : {
        name: "Fell Child",
        Hp: 10,
        Str: 10,
        Mag: 25,
        Dex: 10,
        Spd: 5,
        Def: 10,
        Res: 25,
        Lck: 0,
        Bld: 0,
        caps: {
            Hp: 48,
            Str: 35,
            Mag: 48,
            Dex: 36,
            Spd: 33,
            Def: 25,
            Res: 41,
            Lck: 30,
            Bld: 11,
        },
        unique: true,
    },
    "Avenir" : {
        name: "Avenir",
        Hp: 15,
        Str: 15,
        Mag: 0,
        Dex: 5,
        Spd: 10,
        Def: 25,
        Res: 5,
        Lck: 20,
        Bld: 5,
        caps: {
            Hp: 71,
            Str: 45,
            Mag: 20,
            Dex: 33,
            Spd: 35,
            Def: 37,
            Res: 21,
            Lck: 45,
            Bld: 16,
        },
        unique: true,
    },
    "Vidame" : {
        name: "Vidame",
        Hp: 5,
        Str: 10,
        Mag: 15,
        Dex: 5,
        Spd: 5,
        Def: 5,
        Res: 15,
        Lck: 20,
        Bld: 0,
        caps: {
            Hp: 56,
            Str: 38,
            Mag: 37,
            Dex: 29,
            Spd: 41,
            Def: 27,
            Res: 35,
            Lck: 50,
            Bld: 11,
        },
        unique: true,
    },
    "Successeur" : {
        name: "Successeur",
        Hp: 15,
        Str: 20,
        Mag: 0,
        Dex: 10,
        Spd: 15,
        Def: 15,
        Res: 0,
        Lck: 10,
        Bld: 5,
        caps: {
            Hp: 77,
            Str: 43,
            Mag: 23,
            Dex: 23,
            Spd: 38,
            Def: 38,
            Res: 20,
            Lck: 25,
            Bld: 20,
        },
        unique: true,
    },
    "Tireur d'elite" : {
        name: "Tireur d'elite",
        Hp: 10,
        Str: 10,
        Mag: 0,
        Dex: 30,
        Spd: 10,
        Def: 15,
        Res: 5,
        Lck: 5,
        Bld: 0,
        caps: {
            Hp: 68,
            Str: 41,
            Mag: 20,
            Dex: 41,
            Spd: 40,
            Def: 29,
            Res: 19,
            Lck: 30,
            Bld: 15,
        },
        unique: true,
    },
    "Lindwurm" : {
        name: "Lindwurm",
        Hp: 5,
        Str: 0,
        Mag: 20,
        Dex: 0,
        Spd: 0,
        Def: 10,
        Res: 20,
        Lck: 0,
        Bld: 0,
        caps: {
            Hp: 60,
            Str: 31,
            Mag: 40,
            Dex: 25,
            Spd: 34,
            Def: 31,
            Res: 40,
            Lck: 20,
            Bld: 15,
        },
        unique: true,
    },
    "Sleipnir Rider" : {
        name: "Sleipnir Rider",
        Hp: 0,
        Str: 0,
        Mag: 20,
        Dex: 15,
        Spd: 15,
        Def: 0,
        Res: 30,
        Lck: 15,
        Bld: 0,
        caps: {
            Hp: 47,
            Str: 26,
            Mag: 39,
            Dex: 36,
            Spd: 45,
            Def: 19,
            Res: 51,
            Lck: 53,
            Bld: 11,
        },
        unique: true,
    },
    "Picket" : {
        name: "Picket",
        Hp: 10,
        Str: 15,
        Mag: 0,
        Dex: 10,
        Spd: 10,
        Def: 20,
        Res: 5,
        Lck: 5,
        Bld: 5,
        caps: {
            Hp: 63,
            Str: 35,
            Mag: 27,
            Dex: 47,
            Spd: 41,
            Def: 33,
            Res: 26,
            Lck: 37,
            Bld: 12,
        },
        unique: true,
    },
    "Cupido" : {
        name: "Cupido",
        Hp: 10,
        Str: 5,
        Mag: 5,
        Dex: 20,
        Spd: 20,
        Def: 5,
        Res: 20,
        Lck: 0,
        Bld: 0,
        caps: {
            Hp: 67,
            Str: 35,
            Mag: 28,
            Dex: 33,
            Spd: 49,
            Def: 28,
            Res: 31,
            Lck: 33,
            Bld: 16,
        },
        unique: true,
    },
    "Swordmaster" : {
        name: "Swordmaster",
        Hp: 10,
        Str: 10,
        Mag: 0,
        Dex: 15,
        Spd: 20,
        Def: 0,
        Res: 15,
        Lck: 10,
        Bld: 0,
        caps: {
            Hp: 67,
            Str: 40,
            Mag: 20,
            Dex: 37,
            Spd: 41,
            Def: 27,
            Res: 22,
            Lck: 33,
            Bld: 12,
        },
        unique: false,
    },
    "Halberdier" : {
        name: "Halberdier",
        Hp: 10,
        Str: 15,
        Mag: 5,
        Dex: 20,
        Spd: 10,
        Def: 15,
        Res: 5,
        Lck: 5,
        Bld: 0,
        caps: {
            Hp: 76,
            Str: 46,
            Mag: 29,
            Dex: 47,
            Spd: 36,
            Def: 35,
            Res: 25,
            Lck: 25,
            Bld: 15,
        },
        unique: false,
    },
    "Royal Knight" : {
        name: "Royal Knight",
        Hp: 5,
        Str: 10,
        Mag: 15,
        Dex: 15,
        Spd: 15,
        Def: 5,
        Res: 20,
        Lck: 10,
        Bld: 0,
        caps: {
            Hp: 69,
            Str: 43,
            Mag: 39,
            Dex: 47,
            Spd: 40,
            Def: 28,
            Res: 36,
            Lck: 32,
            Bld: 12,
        },
        unique: false,
    },
    "Hero" : {
        name: "Hero",
        Hp: 15,
        Str: 15,
        Mag: 0,
        Dex: 10,
        Spd: 15,
        Def: 0,
        Res: 10,
        Lck: 15,
        Bld: 0,
        caps: {
            Hp: 75,
            Str: 45,
            Mag: 20,
            Dex: 37,
            Spd: 41,
            Def: 34,
            Res: 22,
            Lck: 33,
            Bld: 16,
        },
        unique: false,
    },
    "Berserker" : {
        name: "Berserker",
        Hp: 30,
        Str: 30,
        Mag: 0,
        Dex: 5,
        Spd: 10,
        Def: 5,
        Res: 0,
        Lck: 0,
        Bld: 10,
        caps: {
            Hp: 96,
            Str: 49,
            Mag: 17,
            Dex: 23,
            Spd: 29,
            Def: 20,
            Res: 11,
            Lck: 23,
            Bld: 24,
        },
        unique: false,
    },
    "Warrior" : {
        name: "Warrior",
        Hp: 25,
        Str: 20,
        Mag: 0,
        Dex: 10,
        Spd: 15,
        Def: 10,
        Res: 5,
        Lck: 0,
        Bld: 5,
        caps: {
            Hp: 94,
            Str: 46,
            Mag: 20,
            Dex: 30,
            Spd: 33,
            Def: 27,
            Res: 18,
            Lck: 23,
            Bld: 20,
        },
        unique: false,
    },
    "Sniper" : {
        name: "Sniper",
        Hp: 15,
        Str: 15,
        Mag: 0,
        Dex: 30,
        Spd: 10,
        Def: 10,
        Res: 0,
        Lck: 10,
        Bld: 0,
        caps: {
            Hp: 68,
            Str: 45,
            Mag: 20,
            Dex: 52,
            Spd: 32,
            Def: 29,
            Res: 24,
            Lck: 28,
            Bld: 14,
        },
        unique: false,
    },
    "Bow Knight" : {
        name: "Bow Knight",
        Hp: 10,
        Str: 10,
        Mag: 0,
        Dex: 20,
        Spd: 20,
        Def: 0,
        Res: 15,
        Lck: 15,
        Bld: 0,
        caps: {
            Hp: 68,
            Str: 38,
            Mag: 23,
            Dex: 45,
            Spd: 37,
            Def: 23,
            Res: 29,
            Lck: 30,
            Bld: 14,
        },
        unique: false,
    },
    "General" : {
        name: "General",
        Hp: 25,
        Str: 20,
        Mag: 0,
        Dex: 10,
        Spd: 0,
        Def: 30,
        Res: 0,
        Lck: 0,
        Bld: 10,
        caps: {
            Hp: 86,
            Str: 47,
            Mag: 16,
            Dex: 39,
            Spd: 17,
            Def: 55,
            Res: 16,
            Lck: 25,
            Bld: 25,
        },
        unique: false,
    },
    "Great Knight" : {
        name: "Great Knight",
        Hp: 20,
        Str: 15,
        Mag: 0,
        Dex: 15,
        Spd: 0,
        Def: 25,
        Res: 10,
        Lck: 5,
        Bld: 5,
        caps: {
            Hp: 75,
            Str: 42,
            Mag: 19,
            Dex: 43,
            Spd: 25,
            Def: 51,
            Res: 22,
            Lck: 30,
            Bld: 20,
        },
        unique: false,
    },
    "Paladin" : {
        name: "Paladin",
        Hp: 15,
        Str: 15,
        Mag: 0,
        Dex: 10,
        Spd: 15,
        Def: 15,
        Res: 15,
        Lck: 10,
        Bld: 0,
        caps: {
            Hp: 77,
            Str: 45,
            Mag: 21,
            Dex: 45,
            Spd: 37,
            Def: 35,
            Res: 29,
            Lck: 30,
            Bld: 16,
        },
        unique: false,
    },
    "Wolf Knight" : {
        name: "Wolf Knight",
        Hp: 10,
        Str: 5,
        Mag: 0,
        Dex: 15,
        Spd: 20,
        Def: 5,
        Res: 20,
        Lck: 20,
        Bld: 0,
        caps: {
            Hp: 69,
            Str: 40,
            Mag: 26,
            Dex: 41,
            Spd: 45,
            Def: 27,
            Res: 33,
            Lck: 34,
            Bld: 12,
        },
        unique: false,
    },
    "Sage" : {
        name: "Sage",
        Hp: 0,
        Str: 0,
        Mag: 30,
        Dex: 5,
        Spd: 0,
        Def: 0,
        Res: 30,
        Lck: 15,
        Bld: 0,
        caps: {
            Hp: 43,
            Str: 26,
            Mag: 48,
            Dex: 34,
            Spd: 30,
            Def: 20,
            Res: 44,
            Lck: 30,
            Bld: 11,
        },
        unique: false,
    },
    "Mage Knight" : {
        name: "Mage Knight",
        Hp: 5,
        Str: 5,
        Mag: 25,
        Dex: 0,
        Spd: 5,
        Def: 10,
        Res: 25,
        Lck: 5,
        Bld: 0,
        caps: {
            Hp: 47,
            Str: 35,
            Mag: 40,
            Dex: 28,
            Spd: 32,
            Def: 26,
            Res: 40,
            Lck: 24,
            Bld: 12,
        },
        unique: false,
    },
    "Martial Master" : {
        name: "Martial Master",
        Hp: 5,
        Str: 10,
        Mag: 20,
        Dex: 0,
        Spd: 0,
        Def: 15,
        Res: 25,
        Lck: 10,
        Bld: 0,
        caps: {
            Hp: 66,
            Str: 38,
            Mag: 41,
            Dex: 26,
            Spd: 28,
            Def: 27,
            Res: 39,
            Lck: 29,
            Bld: 15,
        },
        unique: false,
    },
    "High Priest" : {
        name: "High Priest",
        Hp: 0,
        Str: 0,
        Mag: 25,
        Dex: 0,
        Spd: 5,
        Def: 0,
        Res: 30,
        Lck: 30,
        Bld: 0,
        caps: {
            Hp: 55,
            Str: 28,
            Mag: 45,
            Dex: 31,
            Spd: 32,
            Def: 20,
            Res: 48,
            Lck: 38,
            Bld: 13,
        },
        unique: false,
    },
    "Griffin Knight" : {
        name: "Griffin Knight",
        Hp: 0,
        Str: 10,
        Mag: 15,
        Dex: 15,
        Spd: 20,
        Def: 0,
        Res: 15,
        Lck: 15,
        Bld: 0,
        caps: {
            Hp: 68,
            Str: 40,
            Mag: 37,
            Dex: 48,
            Spd: 49,
            Def: 27,
            Res: 35,
            Lck: 35,
            Bld: 14,
        },
        unique: false,
    },
    "Wyvern Knight" : {
        name: "Wyvern Knight",
        Hp: 20,
        Str: 20,
        Mag: 0,
        Dex: 10,
        Spd: 5,
        Def: 20,
        Res: 5,
        Lck: 5,
        Bld: 5,
        caps: {
            Hp: 83,
            Str: 46,
            Mag: 31,
            Dex: 43,
            Spd: 38,
            Def: 35,
            Res: 22,
            Lck: 25,
            Bld: 18,
        },
        unique: false,
    },
    "Thief" : {
        name: "Thief",
        Hp: 5,
        Str: 10,
        Mag: 0,
        Dex: 20,
        Spd: 15,
        Def: 15,
        Res: 5,
        Lck: 15,
        Bld: 0,
        caps: {
            Hp: 60,
            Str: 43,
            Mag: 22,
            Dex: 51,
            Spd: 42,
            Def: 33,
            Res: 23,
            Lck: 30,
            Bld: 13,
        },
        unique: false,
    },
    "Dancer" : {
        name: "Dancer",
        Hp: 5,
        Str: 10,
        Mag: 0,
        Dex: 5,
        Spd: 15,
        Def: 10,
        Res: 20,
        Lck: 20,
        Bld: 0,
        caps: {
            Hp: 64,
            Str: 36,
            Mag: 31,
            Dex: 29,
            Spd: 43,
            Def: 24,
            Res: 26,
            Lck: 39,
            Bld: 15,
        },
        unique: true,
    },
}

export default promotes;
